#!/bin/sh
. /etc/clearwater/config
smtp_password_escaped=`echo $smtp_password | sed -e 's/\//\\\\\//g'`
sed -e 's/^\(SIP_DIGEST_REALM\) = .*$/\1 = "'$home_domain'"/g' \
    -e 's/^\(HOMESTEAD_URL\) = .*$/\1 = "'$hs_hostname'"/g' \
    -e 's/^\(XDM_URL\) = .*$/\1 = "'$xdms_hostname'"/g' \
    -e 's/^\(SMTP_SMARTHOST\) = .*$/\1 = "'$smtp_smarthost'"/g' \
    -e 's/^\(SMTP_USERNAME\) = .*$/\1 = "'$smtp_username'"/g' \
    -e 's/^\(SMTP_PASSWORD\) = .*$/\1 = "'$smtp_password_escaped'"/g' \
    -e 's/^\(EMAIL_RECOVERY_SENDER\) = .*$/\1 = "'$email_recovery_sender'"/g' \
    -e 's/^\(SIGNUP_CODE\) = .*$/\1 = "'$signup_key'"/g' \
    -e 's/^\(COOKIE_SECRET\) = .*$/\1 = "'$ellis_cookie_key'"/g' \
    -e 's/^\(API_KEY\) = .*$/\1 = "'$ellis_api_key'"/g' \
    </usr/share/clearwater/ellis/src/metaswitch/ellis/local_settings.py >/tmp/local_settings.py.$$
cp /tmp/local_settings.py.$$ /usr/share/clearwater/ellis/src/metaswitch/ellis/local_settings.py
mv /tmp/local_settings.py.$$ /usr/share/clearwater/ellis/env/lib/python2.7/site-packages/ellis-0.1-py2.7.egg/metaswitch/ellis/local_settings.py
